spring:
  application:
    name: my-spring-app

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # Database Configuration
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luanvan?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: baong
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# environment variables
app:
  vars:
    dockerhub_username: nguyengiabao1203